### ISSUE TITLE
when_any allows proceeding workflow ahead, even when all tasks fail

### ISSUE THREAD

**Issue by DeepanshuA** [microsoft/durabletask-python#12]
How to Replicate:
1. Create an orchestrator `my_wf`.
2. Create an activity that always fails, let's say `fail_act_1` - it takes an orderPayload input
3. Create another activity that again always fails, let's say `fail_act_2` - it takes an orderPayload input
4. In `my_wf`, call when_any, something like this:
```
yield when_any([ctx.call_activity(fail_act_1, input=orderPayload),
                                  ctx.call_activity(fail_act_2, input=orderPayload)])

```

After calling when_any, call some other activity, which always passes and takes some input:
```
    yield ctx.call_activity(pass_act, input=some_inp)
```

I would expect that pass_act is never called and orchestrator fails after when_any, as both of the activities in when_any are deemed to fail.
But, In Actual, orchestrator goes ahead and calls pass_act.

**Comment by cgillum** [comment]
@DeepanshuA This behavior is actually by design. The result of `yield when_any(x, y)` is whichever task completed first. For example, `when_any` might return the task for `fail_act_1`. The failure should only happen when someone tries to yield the task for `fail_act_1` or `fail_act_2`. The call to `yield when_any(x, y)` itself is never expected to fail.
